/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ange_ndkdemo_ndk_Ndk */

#ifndef _Included_com_ange_ndkdemo_ndk_Ndk
#define _Included_com_ange_ndkdemo_ndk_Ndk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ange_ndkdemo_ndk_Ndk
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ange_ndkdemo_ndk_Ndk_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_ange_ndkdemo_ndk_Ndk
 * Method:    getString_From_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ange_ndkdemo_ndk_Ndk_getString_1From_1c
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
